### ISSUE TITLE
Allow for optional closing tags

### ISSUE THREAD

**Issue by carolinapowers** [pluralsight/htmlTagValidator#15]
- [ ] Allow for user to optionally include or omit closing tags on the elements that accept optional closing tags, such as the `<option>` tag.

![image](https://cloud.githubusercontent.com/assets/10137641/20438171/9741e522-ad84-11e6-8c58-a10765a4c598.png)

**Comment by renz45** [comment]
Here is the list of valid optional closing tag elements: 

* body
* colgroup
* dd
* dt
* head
* html
* li
* optgroup
* option
* p
* tbody
* td
* tfoot
* th
* thead

**Comment by renz45** [comment]
This is my wip: https://github.com/codeschool/htmlTagValidator/commits/optional_closing_tags
Turns out it's a really hard thing to match on. The optional closing tags functionally use parent elements, subsequent sibling elements, or EOF as closing tags. So for example `<li>` will auto close if another sequential `<li>` tag is found, or a `</ul>` tag is found.  `<html>` will use the EOF, `<body>` will use `</html>`

I probably can't justify spending much more time on this unless @nwronski wants to pair for a bit and see if we can figure it out.

**Comment by aj-foster** [comment]
Hello forever teammate @carolinapowers 👋🏼 (also hello Adam, Nick, and Sarah if you get notified by this — hope you are well!)

Since nobody at Pluralsight is maintaining this repository and we don't actively use it anymore, I'm going to go ahead and close / archive this to avoid the illusion of support.
